# Generated by Django 3.2.4 on 2021-06-30 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidetitles', models.CharField(max_length=100)),
                ('imge', models.ImageField(upload_to='posts/')),
                ('Suspension', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(default=datetime.timezone)),
            ],
        ),
    ]
