# Generated by Django 3.2.4 on 2021-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imge', models.ImageField(upload_to='posts/')),
                ('titel', models.CharField(max_length=100)),
                ('subtitle', models.TextField(max_length=300)),
                ('comint', models.TextField(max_length=3000)),
            ],
        ),
    ]
