# Generated by Django 3.2.4 on 2021-07-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidetitles', models.CharField(max_length=100)),
                ('imge', models.ImageField(upload_to='home/')),
                ('Suspension', models.TextField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Suspension',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sidetitles',
            new_name='titel',
        ),
        migrations.AlterField(
            model_name='about',
            name='imge',
            field=models.ImageField(upload_to='About/'),
        ),
    ]
